# Based on https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml
name: tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.13']

    steps:
    - uses: actions/checkout@v4

    # Setup Python
    - name: Install dependencies for Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'

    # Install Poetry
    - name: Install poetry
      run: pipx install poetry
    
    # Install deps 
    - run: poetry install

    # Run tests
    - name: Tests
      run: poetry run pytest